### ISSUE TITLE
Default buildout fails

### ISSUE THREAD

**Issue by maethu** [collective/collective.solr#79]
If I bootstrap/buildout the `buildout.cfg` it fails with: 

```
%> ./bin/buildout                                                          ~/pkgs/bern.web/src/collective.solr
Upgraded:
  zc.buildout version 2.3.1;
restarting.
Generated script '/home/userpkgs/bern.web/src/collective.solr/bin/buildout'.
Develop: '/home/userpkgs/bern.web/src/collective.solr/.'
warning: no previously-included files found matching 'better-defaults.diff'
warning: no previously-included files found matching 'bootstrap-buildout.py'
warning: no previously-included files found matching '*.cfg'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching 'docs/Makefile'
warning: no previously-included files found matching '.gitattributes'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.*py.un~' found anywhere in distribution
warning: no files found matching '*.txt'
no previously-included directories found matching 'buildout'
no previously-included directories found matching 'docs/source'
no previously-included directories found matching 'etc'
Getting distribution for 'plone.recipe.codeanalysis==2.0b1'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '**/.DS_Store' found anywhere in distribution
warning: no previously-included files matching '**/__pycache__' found anywhere in distribution
Got plone.recipe.codeanalysis 2.0b1.
Getting distribution for 'flake8==2.4.1'.
zip_safe flag not set; analyzing archive contents...
flake8.reporter: module references __file__
flake8.tests._test_warnings: module references __file__
flake8.tests.test_integration: module references __file__
Got flake8 2.4.1.
Getting distribution for 'check-manifest'.
Got check-manifest 0.25.
Getting distribution for 'collective.recipe.sphinxbuilder'.
warning: no files found matching '*.txt'
warning: no previously-included files matching '*pyc' found anywhere in distribution
Got collective.recipe.sphinxbuilder 0.8.2.
Installing _mr.developer.
Generated script '/home/userpkgs/bern.web/src/collective.solr/bin/develop'.
Installing solr-download.
solr-download: Extracting package to /home/userpkgs/bern.web/src/collective.solr/parts/solr-download
Installing solr-instance.
solr-instance: Generated file 'jetty.xml'.
solr-instance: Generated file 'log4j.properties'.
solr-instance: Generated file 'logging.properties'.
While:
  Installing solr-instance.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/user.buildout/eggs-cache/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/home/user.buildout/eggs-cache/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 626, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/user.buildout/eggs-cache/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1370, in _call
    return f()
  File "/home/user.buildout/eggs-cache/collective.recipe.solrinstance-5.3.2-py2.7.egg/collective/recipe/solrinstance/__init__.py", line 625, in install
    directoryFactory=self.solropts['directoryFactory'],
  File "/home/user.buildout/eggs-cache/collective.recipe.solrinstance-5.3.2-py2.7.egg/collective/recipe/solrinstance/__init__.py", line 471, in generate_solr_conf
    name='solrconfig.xml', **kwargs)
  File "/home/user.buildout/eggs-cache/collective.recipe.solrinstance-5.3.2-py2.7.egg/collective/recipe/solrinstance/__init__.py", line 439, in _generate_from_template
    with open(output_file, 'wb') as outfile:
IOError: [Errno 2] No such file or directory: '/home/userpkgs/bern.web/src/collective.solr/parts/solr-instance/solr/conf/solrconfig.xml'
```

Well, the solrconfig.xml is in `..solr-instance/solr/collection1/conf...`. 
It seems like the receipe does not recognise the right solr version.

Any suggestions how to solve this?

I got it running with collective.receipe.solrinstance 6.0.0b3, but I need *this* test setup to make some contributions.

**Comment by do3cc** [comment]
@saily does he need an older collective.solr?

**Comment by maethu** [comment]
I was able to get build working if I do the following changes:

```diff
diff --git a/solr.cfg b/solr.cfg
index cefec7b..f312fb0 100644
--- a/solr.cfg
+++ b/solr.cfg
@@ -30,6 +30,10 @@ logdir = ${buildout:directory}/var/solr
 default-search-field = default
 default-operator = and
 unique-key = UID
+solr-version = 4
+default-operator = AND
+requestParsers-enableRemoteStreaming = true
+updateLog = true
 java_opts =
   -Dcom.sun.management.jmxremote
   -Djava.rmi.server.hostname=127.0.0.1
diff --git a/versions.cfg b/versions.cfg
index d5e31f5..8bf54e4 100644
--- a/versions.cfg
+++ b/versions.cfg
@@ -11,7 +11,7 @@ pep8 = 1.5.7
 plone.recipe.codeanalysis = 2.0b1

 # Solr
-collective.recipe.solrinstance = 5.3.2
+collective.recipe.solrinstance = 6.0.0b3

 # Misc
 zope.interface = 4.0.5
```

**Comment by tisto** [comment]
@maethu which solr version are you using? I tried c.r.solrinstance 6.x a couple of weeks ago and I had to downgrade to 5.x because it did not really work for me.

**Comment by maethu** [comment]
It uses the solr version defined in https://github.com/collective/collective.solr/blob/master/buildout.cfg#L6

The small changes above are required for c.r.solrinstance 6.0.0b3.

**Comment by maethu** [comment]
I'll close this one since, it has something to to with my machine, it seems others do not experience this issue.
